services:
  web:
    build: .
    container_name: property_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - property_network

  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      POSTGRES_USER: propertyuser
      POSTGRES_PASSWORD: propertypass
      POSTGRES_DB: propertydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6379:6379"
    networks:
      - property_network

volumes:
  postgres_data:

networks:
  property_network:
    driver: bridge
